var response = [
    {
        "id": 5164,
        "seo_name": "pedeset-nijansi-mracniji",
        "title": "Fifty Shades Darker",
        "title_hr": "Pedeset nijansi mračniji",
        "release_date": "2017-02-10",
        "theatre_date": "2017-02-14",
        "small_cover": "2-pedeset-nijansi-mracniji.jpg",
        "large_cover": "3-pedeset-nijansi-mracniji.jpg",
        "image_screenshot": "trenutno-pedeset-nijansi-mracniji.jpg",
        "image_poster": "poster-pedeset-nijansi-mracniji.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "James Foley",
        "scenaristi": "E.L. James, Niall Leonard",
        "glumci": "Dakota Johnson, Jamie Dornan, Tyler Hoechlin",
        "zanrovi": "Drama, Romantika",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5164/3-pedeset-nijansi-mracniji.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5164/trenutno-pedeset-nijansi-mracniji.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5164/poster-pedeset-nijansi-mracniji.jpg"
    },
    {
        "id": 5231,
        "seo_name": "lego-batman-film",
        "title": "The Lego Batman Movie",
        "title_hr": "Lego Batman film",
        "release_date": "2017-02-10",
        "theatre_date": "2017-02-10",
        "small_cover": "2-lego-batman-film.jpg",
        "large_cover": "3-lego-batman-film.jpg",
        "image_screenshot": "trenutno-lego-batman-film.jpg",
        "image_poster": "poster-lego-batman-film.jpg",
        "zemlje": "SAD, Danska",
        "jezici": "Engleski",
        "redatelji": "Chris McKay",
        "scenaristi": "Seth Grahame-Smith, Chris McKenna, Erik Sommers",
        "glumci": "Ralph Fiennes, Jenny Slate, Rosario Dawson",
        "zanrovi": "Akcija, Animirani, Avantura",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 1,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5231/3-lego-batman-film.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5231/trenutno-lego-batman-film.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5231/poster-lego-batman-film.jpg"
    },
    {
        "id": 5142,
        "seo_name": "krug-3",
        "title": "Rings",
        "title_hr": "Krug 3",
        "release_date": "2016-10-28",
        "theatre_date": "2017-02-02",
        "small_cover": "2-krug-3.jpg",
        "large_cover": "3-krug-3.jpg",
        "image_screenshot": "",
        "image_poster": "poster-krug-3.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "F. Javier Gutiérrez",
        "scenaristi": "Jacob Aaron Estes, Akiva Goldsman, David Loucka",
        "glumci": "Laura Wiggins, Aimee Teegarden, Johnny Galecki",
        "zanrovi": "Drama, Horor",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5142/3-krug-3.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5142/poster-krug-3.jpg"
    },
    {
        "id": 5255,
        "seo_name": "lav",
        "title": "Lion",
        "title_hr": "Lav",
        "release_date": "2017-01-06",
        "theatre_date": "2017-02-02",
        "small_cover": "2-lav.jpg",
        "large_cover": "3-lav.jpg",
        "image_screenshot": "trenutno-lav.jpg",
        "image_poster": "poster-lav.jpg",
        "zemlje": "Australija",
        "jezici": "Engleski, Bengali, Hindi",
        "redatelji": "Garth Davis",
        "scenaristi": "Saroo Brierley, Luke Davies",
        "glumci": "Sunny Pawar, Abhishek Bharate, Priyanka Bose",
        "zanrovi": "Drama",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5255/3-lav.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5255/trenutno-lav.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5255/poster-lav.jpg"
    },
    {
        "id": 5269,
        "seo_name": "mjesecina",
        "title": "Moonlight",
        "title_hr": "Mjesečina",
        "release_date": "2016-11-18",
        "theatre_date": "2017-02-02",
        "small_cover": "2-mjesecina.jpg",
        "large_cover": "3-mjesecina.jpg",
        "image_screenshot": "trenutno-mjesecina.jpg",
        "image_poster": "poster-mjesecina.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Barry Jenkins",
        "scenaristi": "Barry Jenkins, Tarell Alvin McCraney",
        "glumci": "Mahershala Ali, Shariff Earp, Duan Sanderson",
        "zanrovi": "Drama",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5269/3-mjesecina.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5269/trenutno-mjesecina.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5269/poster-mjesecina.jpg"
    },
    {
        "id": 5271,
        "seo_name": "pattaya",
        "title": "Pattaya",
        "title_hr": "Pattaya",
        "release_date": "2017-02-02",
        "theatre_date": "2017-02-02",
        "small_cover": "2-pattaya.jpg",
        "large_cover": "3-pattaya.jpg",
        "image_screenshot": "trenutno-pattaya.jpg",
        "image_poster": "poster-pattaya.jpg",
        "zemlje": "Francuska",
        "jezici": "Francuski",
        "redatelji": "Franck Gastambide",
        "scenaristi": "Franck Gastambide, Stéphane Kazandjian",
        "glumci": "Franck Gastambide, Malik Bentalha, Anouar Toubali",
        "zanrovi": "Komedija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5271/3-pattaya.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5271/trenutno-pattaya.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5271/poster-pattaya.jpg"
    },
    {
        "id": 5272,
        "seo_name": "sve-ili-nista",
        "title": "Hell or High Water",
        "title_hr": "Sve ili ništa",
        "release_date": "2016-08-26",
        "theatre_date": "2017-02-02",
        "small_cover": "2-sve-ili-nista.jpg",
        "large_cover": "3-sve-ili-nista.jpg",
        "image_screenshot": "trenutno-sve-ili-nista.jpg",
        "image_poster": "poster-sve-ili-nista.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "David Mackenzie",
        "scenaristi": "Taylor Sheridan",
        "glumci": "Dale Dickey, Ben Foster, Chris Pine",
        "zanrovi": "Kriminalistički, Triler",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5272/3-sve-ili-nista.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5272/trenutno-sve-ili-nista.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5272/poster-sve-ili-nista.jpg"
    },
    {
        "id": 5252,
        "seo_name": "zlato",
        "title": "Gold",
        "title_hr": "Zlato",
        "release_date": "2017-01-27",
        "theatre_date": "2017-01-26",
        "small_cover": "2-zlato.jpg",
        "large_cover": "3-zlato.jpg",
        "image_screenshot": "trenutno-zlato.jpg",
        "image_poster": "poster-zlato.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Stephen Gaghan",
        "scenaristi": "Patrick Massett, John Zinman",
        "glumci": "Bryce Dallas Howard, Matthew McConaughey, Toby Kebbell",
        "zanrovi": "Avantura, Drama, Triler",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5252/3-zlato.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5252/trenutno-zlato.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5252/poster-zlato.jpg"
    },
    {
        "id": 5267,
        "seo_name": "resident-evil-konacno-poglavlje",
        "title": "Resident Evil: The Final Chapter",
        "title_hr": "Resident Evil: Konačno poglavlje",
        "release_date": "2016-12-13",
        "theatre_date": "2017-01-26",
        "small_cover": "2-resident-evil-konacno-poglavlje.jpg",
        "large_cover": "3-resident-evil-konacno-poglavlje.jpg",
        "image_screenshot": "",
        "image_poster": "poster-resident-evil-konacno-poglavlje.jpg",
        "zemlje": "Francuska, Njemačka, Kanada, Australija",
        "jezici": "Engleski",
        "redatelji": "Paul W.S. Anderson",
        "scenaristi": "Paul W.S. Anderson",
        "glumci": "Milla Jovovich, Iain Glen, Ali Larter",
        "zanrovi": "Akcija, Horor, SF",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5267/3-resident-evil-konacno-poglavlje.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5267/poster-resident-evil-konacno-poglavlje.jpg"
    },
    {
        "id": 5268,
        "seo_name": "uzbuna-na-zelenom-vrhu",
        "title": " Uzbuna na Zelenom Vrhu",
        "title_hr": " Uzbuna na Zelenom Vrhu",
        "release_date": "2017-01-26",
        "theatre_date": "2017-01-26",
        "small_cover": "2-uzbuna-na-zelenom-vrhu.jpg",
        "large_cover": "3-uzbuna-na-zelenom-vrhu.jpg",
        "image_screenshot": "",
        "image_poster": "poster-uzbuna-na-zelenom-vrhu.jpg",
        "zemlje": "Hrvatska",
        "jezici": "Hrvatski",
        "redatelji": "Čejen Černić",
        "scenaristi": "Hana Jušić, Čejen Černić, Ivan Kušan",
        "glumci": "Alex Rakoš, Marko Tocilj, Jan Pentek",
        "zanrovi": "Dječji, Misterija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5268/3-uzbuna-na-zelenom-vrhu.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5268/poster-uzbuna-na-zelenom-vrhu.jpg"
    },
    {
        "id": 5207,
        "seo_name": "podvojen",
        "title": "Split",
        "title_hr": "Podvojen",
        "release_date": "2017-01-20",
        "theatre_date": "2017-01-19",
        "small_cover": "2-podvojen.jpg",
        "large_cover": "3-podvojen.jpg",
        "image_screenshot": "trenutno-podvojen.jpg",
        "image_poster": "poster-podvojen.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "M. Night Shyamalan",
        "scenaristi": "M. Night Shyamalan",
        "glumci": "James McAvoy, Anya Taylor-Joy, Haley Lu Richardson",
        "zanrovi": "Horor, Triler",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5207/3-podvojen.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5207/trenutno-podvojen.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5207/poster-podvojen.jpg"
    },
    {
        "id": 5208,
        "seo_name": "xxx-povratak-xandera-cagea",
        "title": "xXx: Return of Xander Cage",
        "title_hr": "xXx: Povratak Xandera Cagea",
        "release_date": "2017-01-20",
        "theatre_date": "2017-01-19",
        "small_cover": "2-xxx-povratak-xandera-cagea.jpg",
        "large_cover": "3-xxx-povratak-xandera-cagea.jpg",
        "image_screenshot": "trenutno-xxx-povratak-xandera-cagea.jpg",
        "image_poster": "poster-xxx-povratak-xandera-cagea.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "D.J. Caruso",
        "scenaristi": "F. Scott Frazier, Chad St. John, Rich Wilkes",
        "glumci": "Nina Dobrev, Ruby Rose, Vin Diesel",
        "zanrovi": "Akcija, Avantura, Triler",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5208/3-xxx-povratak-xandera-cagea.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5208/trenutno-xxx-povratak-xandera-cagea.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5208/poster-xxx-povratak-xandera-cagea.jpg"
    },
    {
        "id": 5253,
        "seo_name": "prsten-k-sebi",
        "title": "Bling",
        "title_hr": "Prste(n) k sebi",
        "release_date": "2016-08-04",
        "theatre_date": "2017-01-19",
        "small_cover": "2-prsten-k-sebi.jpg",
        "large_cover": "3-prsten-k-sebi.jpg",
        "image_screenshot": "trenutno-prsten-k-sebi.jpg",
        "image_poster": "poster-prsten-k-sebi.jpg",
        "zemlje": "SAD, Sjeverna Koreja",
        "jezici": "Engleski",
        "redatelji": "Kyung Ho Lee, Wonjae Lee",
        "scenaristi": "Chris Denk, Hyunjoong Kim, Kyung Ho Lee",
        "glumci": "Taylor Kitsch, Jennette McCurdy, James Woods",
        "zanrovi": "Akcija, Animirani",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 1,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5253/3-prsten-k-sebi.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5253/trenutno-prsten-k-sebi.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5253/poster-prsten-k-sebi.jpg"
    },
    {
        "id": 5266,
        "seo_name": "jackie2017",
        "title": "Jackie",
        "title_hr": "Jackie",
        "release_date": "2016-12-02",
        "theatre_date": "2017-01-19",
        "small_cover": "2-jackie2017.jpg",
        "large_cover": "3-jackie2017.jpg",
        "image_screenshot": "trenutno-jackie2017.jpg",
        "image_poster": "poster-jackie2017.jpg",
        "zemlje": "SAD, Francuska, Chile",
        "jezici": "Engleski, Španjolski",
        "redatelji": "Pablo Larraín",
        "scenaristi": "Noah Oppenheim",
        "glumci": "Natalie Portman, Peter Sarsgaard, Greta Gerwig",
        "zanrovi": "Biografski, Drama",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5266/3-jackie2017.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5266/trenutno-jackie2017.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5266/poster-jackie2017.jpg"
    },
    {
        "id": 5250,
        "seo_name": "obitelj-bez-kocnica",
        "title": "À fond",
        "title_hr": "Obitelj bez kočnica",
        "release_date": "2016-12-21",
        "theatre_date": "2017-01-12",
        "small_cover": "2-obitelj-bez-kocnica.jpg",
        "large_cover": "3-obitelj-bez-kocnica.jpg",
        "image_screenshot": "trenutno-obitelj-bez-kocnica.jpg",
        "image_poster": "poster-obitelj-bez-kocnica.jpg",
        "zemlje": "Francuska",
        "jezici": "Francuski",
        "redatelji": "Nicolas Benamou",
        "scenaristi": "Nicolas Benamou, Frédéric Jardin, Fabrice Roger-Lacan",
        "glumci": "José Garcia, André Dussollier, Caroline Vigneaux",
        "zanrovi": "Komedija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5250/3-obitelj-bez-kocnica.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5250/trenutno-obitelj-bez-kocnica.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5250/poster-obitelj-bez-kocnica.jpg"
    },
    {
        "id": 5251,
        "seo_name": "zakon-noci",
        "title": "Live by Night ",
        "title_hr": "Zakon noći",
        "release_date": "2017-01-12",
        "theatre_date": "2017-01-12",
        "small_cover": "2-zakon-noci.jpg",
        "large_cover": "3-zakon-noci.jpg",
        "image_screenshot": "trenutno-zakon-noci.jpg",
        "image_poster": "poster-zakon-noci.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Ben Affleck",
        "scenaristi": "Dennis Lehane, Ben Affleck",
        "glumci": "Ben Affleck, Scott Eastwood, Zoe Saldana",
        "zanrovi": "Drama, Krimi",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5251/3-zakon-noci.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5251/trenutno-zakon-noci.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5251/poster-zakon-noci.jpg"
    },
    {
        "id": 5247,
        "seo_name": "la-la-land",
        "title": "La La Land",
        "title_hr": "La La Land",
        "release_date": "2017-01-05",
        "theatre_date": "2017-01-05",
        "small_cover": "2-la-la-land.jpg",
        "large_cover": "3-la-la-land.jpg",
        "image_screenshot": "trenutno-la-la-land.jpg",
        "image_poster": "poster-la-la-land.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Damien Chazelle",
        "scenaristi": "Damien Chazelle",
        "glumci": "Ryan Gosling, Emma Stone, Amiée Conn",
        "zanrovi": "Drama, Glazbeni, Komedija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5247/3-la-la-land.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5247/trenutno-la-la-land.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5247/poster-la-la-land.jpg"
    },
    {
        "id": 5248,
        "seo_name": "obdukcija-jane-doe",
        "title": "The Autopsy of Jane Doe",
        "title_hr": "Obdukcija Jane Doe",
        "release_date": "2017-01-05",
        "theatre_date": "2017-01-05",
        "small_cover": "2-obdukcija-jane-doe.jpg",
        "large_cover": "3-obdukcija-jane-doe.jpg",
        "image_screenshot": "trenutno-obdukcija-jane-doe.jpg",
        "image_poster": "poster-obdukcija-jane-doe.jpg",
        "zemlje": "Ujedinjeno Kraljevstvo",
        "jezici": "Engleski",
        "redatelji": "André Øvredal",
        "scenaristi": "Ian B. Goldberg, Richard Naing",
        "glumci": "Emile Hirsch, Brian Cox, Ophelia Lovibond",
        "zanrovi": "Horor",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5248/3-obdukcija-jane-doe.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5248/trenutno-obdukcija-jane-doe.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5248/poster-obdukcija-jane-doe.jpg"
    },
    {
        "id": 5175,
        "seo_name": "putnici-2016",
        "title": "Passengers",
        "title_hr": "Putnici",
        "release_date": "2016-10-21",
        "theatre_date": "2016-12-29",
        "small_cover": "2-putnici-2016.jpg",
        "large_cover": "3-putnici-2016.jpg",
        "image_screenshot": "trenutno-putnici-2016.jpg",
        "image_poster": "poster-putnici-2016.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Morten Tyldum",
        "scenaristi": "Jon Spaihts",
        "glumci": "Jennifer Lawrence, Chris Pratt, Michael Sheen",
        "zanrovi": "Avantura, Drama, SF",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5175/3-putnici-2016.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5175/trenutno-putnici-2016.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5175/poster-putnici-2016.jpg"
    },
    {
        "id": 5197,
        "seo_name": "assassins-creed",
        "title": "Assassin's Creed",
        "title_hr": "Assassin's Creed",
        "release_date": "2016-12-21",
        "theatre_date": "2016-12-29",
        "small_cover": "2-assassins-creed.jpg",
        "large_cover": "3-assassins-creed.jpg",
        "image_screenshot": "trenutno-assassins-creed.jpg",
        "image_poster": "poster-assassins-creed.jpg",
        "zemlje": "SAD, Francuska, Hong Kong, Ujedinjeno Kraljevstvo",
        "jezici": "Engleski, Španjolski",
        "redatelji": "Justin Kurzel",
        "scenaristi": "Bill Collage, Adam Cooper, Michael Lesslie",
        "glumci": "Michael Fassbender, Marion Cotillard, Ariane Labed",
        "zanrovi": "Akcija, Avantura, Fantazija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5197/3-assassins-creed.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5197/trenutno-assassins-creed.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5197/poster-assassins-creed.jpg"
    },
    {
        "id": 5162,
        "seo_name": "snjezna-kraljica-3-vatra-i-led",
        "title": "The Snow Queen 3",
        "title_hr": "Snježna kraljica 3: Vatra i led",
        "release_date": "2016-12-22",
        "theatre_date": "2016-12-22",
        "small_cover": "2-snjezna-kraljica-3-vatra-i-led.jpg",
        "large_cover": "3-snjezna-kraljica-3-vatra-i-led.jpg",
        "image_screenshot": "",
        "image_poster": "poster-snjezna-kraljica-3-vatra-i-led.jpg",
        "zemlje": "Rusija",
        "jezici": "Ruski",
        "redatelji": "Aleksey Tsitsilin",
        "scenaristi": "Andrey Korenkov, Robert Lence, Vladimir Nikolaev",
        "glumci": "Nema informacija",
        "zanrovi": "Animirani, Avantura, Obiteljski",
        "trid": 1,
        "imax": 0,
        "sinkronizirano": 1,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5162/3-snjezna-kraljica-3-vatra-i-led.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5162/poster-snjezna-kraljica-3-vatra-i-led.jpg"
    },
    {
        "id": 5227,
        "seo_name": "zasto-bas-on",
        "title": "Why Him?",
        "title_hr": "Zašto baš on?",
        "release_date": "2016-12-22",
        "theatre_date": "2016-12-22",
        "small_cover": "2-zasto-bas-on.jpg",
        "large_cover": "3-zasto-bas-on.jpg",
        "image_screenshot": "trenutno-zasto-bas-on.jpg",
        "image_poster": "poster-zasto-bas-on.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "John Hamburg",
        "scenaristi": "Jonah Hill, John Hamburg, Ian Helfer",
        "glumci": "Zoey Deutch, Bryan Cranston, James Franco",
        "zanrovi": "Komedija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5227/3-zasto-bas-on.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5227/trenutno-zasto-bas-on.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5227/poster-zasto-bas-on.jpg"
    },
    {
        "id": 5236,
        "seo_name": "balerina-i-viktor",
        "title": "Ballerina",
        "title_hr": "Balerina i Viktor",
        "release_date": "2016-12-22",
        "theatre_date": "2016-12-22",
        "small_cover": "2-balerina-i-viktor.jpg",
        "large_cover": "3-balerina-i-viktor.jpg",
        "image_screenshot": "trenutno-balerina-i-viktor.jpg",
        "image_poster": "poster-balerina-i-viktor.jpg",
        "zemlje": "Francuska, Kanada",
        "jezici": "Engleski",
        "redatelji": "Eric Summer, Éric Warin",
        "scenaristi": "Carol Noble, Eric Summer, Laurent Zeitoun",
        "glumci": "Elle Fanning, Dane DeHaan, Carly Rae Jepsen",
        "zanrovi": "Animirani, Avantura, Obiteljski",
        "trid": 1,
        "imax": 0,
        "sinkronizirano": 1,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5236/3-balerina-i-viktor.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5236/trenutno-balerina-i-viktor.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5236/poster-balerina-i-viktor.jpg"
    },
    {
        "id": 5232,
        "seo_name": "pjevajte-s-nama",
        "title": "Sing",
        "title_hr": "Pjevajte s nama",
        "release_date": "2016-12-08",
        "theatre_date": "2016-12-08",
        "small_cover": "2-pjevajte-s-nama.jpg",
        "large_cover": "3-pjevajte-s-nama.jpg",
        "image_screenshot": "trenutno-pjevajte-s-nama.jpg",
        "image_poster": "poster-pjevajte-s-nama.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Garth Jennings, Christophe Lourdelet",
        "scenaristi": "Garth Jennings",
        "glumci": "Matthew McConaughey, Reese Witherspoon, Seth MacFarlane",
        "zanrovi": "Animirani",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 1,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5232/3-pjevajte-s-nama.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5232/trenutno-pjevajte-s-nama.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5232/poster-pjevajte-s-nama.jpg"
    },
    {
        "id": 5144,
        "seo_name": "dolazak",
        "title": "Arrival",
        "title_hr": "Dolazak",
        "release_date": "2016-11-11",
        "theatre_date": "2016-12-01",
        "small_cover": "2-dolazak.jpg",
        "large_cover": "3-dolazak.jpg",
        "image_screenshot": "trenutno-dolazak.jpg",
        "image_poster": "poster-dolazak.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Denis Villeneuve",
        "scenaristi": "Ted Chiang",
        "glumci": "Amy Adams, Jeremy Renner, Forest Whitaker",
        "zanrovi": "Drama, Misterija, SF",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5144/3-dolazak.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5144/trenutno-dolazak.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5144/poster-dolazak.jpg"
    },
    {
        "id": 5187,
        "seo_name": "stado",
        "title": "Stado",
        "title_hr": "Stado",
        "release_date": "2016-11-24",
        "theatre_date": "2016-12-01",
        "small_cover": "2-stado.jpg",
        "large_cover": "3-stado.jpg",
        "image_screenshot": "trenutno-stado.jpg",
        "image_poster": "poster-stado.jpg",
        "zemlje": "Srbija",
        "jezici": "Srpski",
        "redatelji": "Nikola Kojo",
        "scenaristi": "Nebojsa Romcevic",
        "glumci": "Nikola Kojo, Vesna Trivalić, Zoran Cvijanović",
        "zanrovi": "Komedija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5187/3-stado.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5187/trenutno-stado.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5187/poster-stado.jpg"
    },
    {
        "id": 5172,
        "seo_name": "vaiana",
        "title": "Moana",
        "title_hr": "Vaiana",
        "release_date": "2016-11-24",
        "theatre_date": "2016-11-24",
        "small_cover": "2-vaiana.jpg",
        "large_cover": "3-vaiana.jpg",
        "image_screenshot": "trenutno-vaiana.jpg",
        "image_poster": "poster-vaiana.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Ron Clements, John Musker, Don Hall",
        "scenaristi": "Jared Bush, Ron Clements, John Musker",
        "glumci": "Dwayne Johnson, Alan Tudyk, Nicole Scherzinger",
        "zanrovi": "Animirani, Avantura",
        "trid": 1,
        "imax": 0,
        "sinkronizirano": 1,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5172/3-vaiana.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5172/trenutno-vaiana.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5172/poster-vaiana.jpg"
    },
    {
        "id": 5167,
        "seo_name": "hacksaw-ridge",
        "title": "Hacksaw Ridge",
        "title_hr": "Greben spašenih",
        "release_date": "2016-11-04",
        "theatre_date": "2016-11-10",
        "small_cover": "2-hacksaw-ridge.jpg",
        "large_cover": "3-hacksaw-ridge.jpg",
        "image_screenshot": "trenutno-hacksaw-ridge.jpg",
        "image_poster": "poster-hacksaw-ridge.jpg",
        "zemlje": "SAD, Australija",
        "jezici": "Engleski",
        "redatelji": "Mel Gibson",
        "scenaristi": "Andrew Knight, Robert Schenkkan",
        "glumci": "Teresa Palmer, Andrew Garfield, Luke Bracey",
        "zanrovi": "Biografski, Drama, Ratni",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5167/3-hacksaw-ridge.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5167/trenutno-hacksaw-ridge.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5167/poster-hacksaw-ridge.jpg"
    },
    {
        "id": 5098,
        "seo_name": "trolovi",
        "title": "Trolls",
        "title_hr": "Trolovi",
        "release_date": "2016-11-03",
        "theatre_date": "2016-11-03",
        "small_cover": "2-trolovi.jpg",
        "large_cover": "3-trolovi.jpg",
        "image_screenshot": "trenutno-trolovi.jpg",
        "image_poster": "poster-trolovi.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Mike Mitchell, Walt Dohrn",
        "scenaristi": "Jonathan Aibel, Glenn Berger",
        "glumci": "Anna Kendrick, Zooey Deschanel, Justin Timberlake",
        "zanrovi": "Animirani, Avantura, Obiteljski",
        "trid": 1,
        "imax": 0,
        "sinkronizirano": 1,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5098/3-trolovi.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5098/trenutno-trolovi.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5098/poster-trolovi.jpg"
    },
    {
        "id": 5159,
        "seo_name": "sedam-minuta-nakon-ponoci",
        "title": "A Monster Calls",
        "title_hr": "Sedam minuta nakon ponoći",
        "release_date": "2016-10-20",
        "theatre_date": "2016-10-20",
        "small_cover": "2-sedam-minuta-nakon-ponoci.jpg",
        "large_cover": "3-sedam-minuta-nakon-ponoci.jpg",
        "image_screenshot": "trenutno-sedam-minuta-nakon-ponoci.jpg",
        "image_poster": "poster-sedam-minuta-nakon-ponoci.jpg",
        "zemlje": "SAD, Španjolska",
        "jezici": "Engleski",
        "redatelji": "J.A. Bayona",
        "scenaristi": "Patrick Ness",
        "glumci": "Felicity Jones, Toby Kebbell, Liam Neeson",
        "zanrovi": "Drama, Fantazija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5159/3-sedam-minuta-nakon-ponoci.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5159/trenutno-sedam-minuta-nakon-ponoci.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5159/poster-sedam-minuta-nakon-ponoci.jpg"
    },
    {
        "id": 5058,
        "seo_name": "florence-foster-jenkins",
        "title": "Florence Foster Jenkins",
        "title_hr": "Neslavno slavna Florence",
        "release_date": "2016-04-23",
        "theatre_date": "2016-10-20",
        "small_cover": "2-florence-foster-jenkins.jpg",
        "large_cover": "3-florence-foster-jenkins.jpg",
        "image_screenshot": "trenutno-florence-foster-jenkins.jpg",
        "image_poster": "poster-florence-foster-jenkins.jpg",
        "zemlje": "Ujedinjeno Kraljevstvo",
        "jezici": "Engleski",
        "redatelji": "Stephen Frears",
        "scenaristi": "Nicholas Martin",
        "glumci": "Rebecca Ferguson, Meryl Streep, Simon Helberg",
        "zanrovi": "Biografski, Drama, Komedija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5058/3-florence-foster-jenkins.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5058/trenutno-florence-foster-jenkins.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5058/poster-florence-foster-jenkins.jpg"
    },
    {
        "id": 5131,
        "seo_name": "ustav-republike-hrvatske",
        "title": "The Constitution",
        "title_hr": "Ustav Republike Hrvatske",
        "release_date": "2016-11-01",
        "theatre_date": "2016-10-13",
        "small_cover": "2-ustav-republike-hrvatske.jpg",
        "large_cover": "3-ustav-republike-hrvatske.jpg",
        "image_screenshot": "trenutno-ustav-republike-hrvatske.jpg",
        "image_poster": "poster-ustav-republike-hrvatske.jpg",
        "zemlje": "Hrvatska",
        "jezici": "Hrvatski",
        "redatelji": "Rajko Grlić",
        "scenaristi": "Rajko Grlić, Ante Tomić",
        "glumci": "Nebojsa Glogovac, Dejan Aćimović, Ksenija Marinković",
        "zanrovi": "Drama, Komedija",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5131/3-ustav-republike-hrvatske.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5131/trenutno-ustav-republike-hrvatske.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5131/poster-ustav-republike-hrvatske.jpg"
    },
    {
        "id": 4801,
        "seo_name": "tajni-zivot-ljubimaca",
        "title": "The Secret Life of Pets",
        "title_hr": "Tajni život ljubimaca",
        "release_date": "2016-06-24",
        "theatre_date": "2016-08-04",
        "small_cover": "2-tajni-zivot-ljubimaca.jpg",
        "large_cover": "3-tajni-zivot-ljubimaca.jpg",
        "image_screenshot": "",
        "image_poster": "poster-tajni-zivot-ljubimaca.jpg",
        "zemlje": "SAD",
        "jezici": "Engleski",
        "redatelji": "Yarrow Cheney, Chris Renaud\t",
        "scenaristi": "Ken Daurio, Brian Lynch, Cinco Paul",
        "glumci": "Ellie Kemper, Lake Bell, Kevin Hart",
        "zanrovi": "Animirani, Komedija, Obiteljski",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/4801/3-tajni-zivot-ljubimaca.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/4801/poster-tajni-zivot-ljubimaca.jpg"
    },
    {
        "id": 5270,
        "seo_name": "ispod-sunca",
        "title": "Under the Sun",
        "title_hr": "Ispod sunca",
        "release_date": "2016-10-27",
        "theatre_date": "0000-00-00",
        "small_cover": "2-ispod-sunca.jpg",
        "large_cover": "3-ispod-sunca.jpg",
        "image_screenshot": "trenutno-ispod-sunca.jpg",
        "image_poster": "poster-ispod-sunca.jpg",
        "zemlje": "Njemačka, Rusija, Češka Republika, Sjeverna Korea",
        "jezici": "Korejski",
        "redatelji": "Vitaliy Manskiy",
        "scenaristi": "Vitaliy Manskiy",
        "glumci": "Lee Zin-Mi, Yu-Yong, Hye-Yong",
        "zanrovi": "Dokumentarni",
        "trid": 0,
        "imax": 0,
        "sinkronizirano": 0,
        "image_cover_url": "http://www.moj-film.hr/data/movie/5270/3-ispod-sunca.jpg",
        "image_screenshot_url": "http://www.moj-film.hr/data/movie/5270/trenutno-ispod-sunca.jpg",
        "image_poster_url": "http://www.moj-film.hr/data/movie/5270/poster-ispod-sunca.jpg"
    }
];


module.exports = {
    getMovie: function () {
        return response;
    }
};

